In [2]:
import numpy as np

In [61]:
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
a.shape

(3, 5)

In [63]:
a.ndim

2

In [64]:
a.dtype

dtype('int32')

In [65]:
a.dtype.name

'int32'

In [66]:
a.itemsize

4

In [67]:
a.size

15

In [68]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [69]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [72]:
#2D array
np2d=np.arange(12).reshape(4,3)
print(np2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [57]:
#2D array
x=[[3.33,3.2,1.4],[1.4,5,5.7]]
nparray=np.array(x)
print(nparray)
print(nparray.dtype)

[[ 3.33  3.2   1.4 ]
 [ 1.4   5.    5.7 ]]
float64


In [4]:
nparray.shape

(2, 3)

In [3]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
np.zeros((5,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [5]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [6]:
np.ones((3,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [73]:
#1D array
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [12]:
#1D array
x=[3.33,3.2,1.4,5]
npx=np.array(x)
npx
print("1st 2 elements : ",npx[:2])
print("last element : ",npx[-1])

1st 2 elements :  [ 3.33  3.2 ]
last element :  5.0


In [16]:
#2D array
np2d=np.array([[1,2,3],
              [4,6,7],
              [1,2,8]])
np2d

array([[1, 2, 3],
       [4, 6, 7],
       [1, 2, 8]])

In [17]:
np2d[1]

array([4, 6, 7])

In [74]:
#3D array
np3d=np.arange(24).reshape(2,3,4)
print(np3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [19]:
#3D array
np3d=np.array([[[1,2,3],
              [4,6,7]],
              [[1,2,8],[5,7,9]]])
np3d

array([[[1, 2, 3],
        [4, 6, 7]],

       [[1, 2, 8],
        [5, 7, 9]]])

In [20]:
np3d[1]

array([[1, 2, 8],
       [5, 7, 9]])

In [21]:
np3d[1,0]

array([1, 2, 8])

In [59]:
x=np.array([2,4,6,10,12])
x
print("sum of all: ",x.sum())
print("product of all: ",x.prod())
print("min of all: ",x.min())
print("max of all: ",x.max())
print("max element is at pos.: ",x.argmax())
print(x[x<10])

sum of all:  34
product of all:  5760
min of all:  2
max of all:  12
max element is at pos.:  4
[2 4 6]


In [86]:
#Element wise operation
x=[[3.33,3.2,1.4],[1.4,5,5.7]]
npx=np.array(x)
npx

array([[ 3.33,  3.2 ,  1.4 ],
       [ 1.4 ,  5.  ,  5.7 ]])

In [28]:
npx*npx # array with same shape each elem squared returned

array([[ 11.0889,  10.24  ,   1.96  ],
       [  1.96  ,  25.    ,  32.49  ]])

In [29]:
npx+npx ## array with same shape each elem added with their own returned

array([[  6.66,   6.4 ,   2.8 ],
       [  2.8 ,  10.  ,  11.4 ]])

In [87]:
npx.min(axis=0) #min of each col

array([ 1.4,  3.2,  1.4])

In [88]:
npx.max(axis=1) #max of each row

array([ 3.33,  5.7 ])

In [90]:
npx.sum(axis=0) #sum of each col

array([ 4.73,  8.2 ,  7.1 ])

In [91]:
npx.cumsum(axis=1) #cumulative sum along each row

array([[  3.33,   6.53,   7.93],
       [  1.4 ,   6.4 ,  12.1 ]])

In [31]:
#array manipulation
#Reshaping
x=np.array([1,2,3,4,5,6,7,8,9,0])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [40]:
x1=x.reshape((5,2))
x1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [37]:
x2=x1.reshape((2,5))
x2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [42]:
x3=x1.flatten()
x3

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [76]:
np1=np.array([[1,4,7],[1.2,3.6,4]])
np2=np.array([[4,7,9],[10,23,50]])
c=np1-np2
c

array([[ -3. ,  -3. ,  -2. ],
       [ -8.8, -19.4, -46. ]])

In [77]:
np1*np2

array([[   4. ,   28. ,   63. ],
       [  12. ,   82.8,  200. ]])

In [79]:
#Random module
outcome=np.random.randint(1,7,size=10)
print(outcome)

[3 5 4 2 2 4 4 2 5 4]


In [80]:
outcome=np.random.randint(1,7,size=(2,5))
print(outcome)

[[6 5 2 4 5]
 [2 4 5 3 5]]


In [81]:
x=[10,20,35,79]
np.random.shuffle(x)
print(x)

[20, 10, 79, 35]


In [84]:
a=np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a*=3
a


array([[3, 3, 3],
       [3, 3, 3]])

In [85]:
b+=a
b

array([[ 3.65330196,  3.52791408,  3.4182933 ],
       [ 3.30724755,  3.39156445,  3.65719928]])

In [43]:
#concatenate of arrays
np1=np.array([[1,4,7],[1.2,3.6,4]])
np2=np.array([[4,7,9],[10,23,50]])

print ("np1")
print (np1)

print("np2")
print(np2)

np1
[[ 1.   4.   7. ]
 [ 1.2  3.6  4. ]]
np2
[[ 4  7  9]
 [10 23 50]]


In [44]:
np3=np.concatenate([np1,np2],axis=0) #v stack
np3

array([[  1. ,   4. ,   7. ],
       [  1.2,   3.6,   4. ],
       [  4. ,   7. ,   9. ],
       [ 10. ,  23. ,  50. ]])

In [45]:
np3=np.vstack((np1,np2))
np3

array([[  1. ,   4. ,   7. ],
       [  1.2,   3.6,   4. ],
       [  4. ,   7. ,   9. ],
       [ 10. ,  23. ,  50. ]])

In [46]:
np4=np.concatenate([np1,np2],axis=1) #H stack
np4

array([[  1. ,   4. ,   7. ,   4. ,   7. ,   9. ],
       [  1.2,   3.6,   4. ,  10. ,  23. ,  50. ]])

In [47]:
np4=np.hstack((np1,np2))
np4

array([[  1. ,   4. ,   7. ,   4. ,   7. ,   9. ],
       [  1.2,   3.6,   4. ,  10. ,  23. ,  50. ]])

In [48]:
#spliting of arrays
np5=np.split(np4,2)
np5

[array([[ 1.,  4.,  7.,  4.,  7.,  9.]]),
 array([[  1.2,   3.6,   4. ,  10. ,  23. ,  50. ]])]

In [50]:
np6=np.split(np3,2)
np6

[array([[ 1. ,  4. ,  7. ],
        [ 1.2,  3.6,  4. ]]), array([[  4.,   7.,   9.],
        [ 10.,  23.,  50.]])]

[5 3 3 4 6 6 6 2 6 5]


[[1 3 6 4 6]
 [6 5 6 2 6]]


[10, 20, 79, 35]
